### ISSUE TITLE
Zaključek projekta ŠIPK

### ISSUE THREAD

**Issue by jaanos** [jaanos/crypto-portal#5]
Ker se s koncem meseca zaključi projekt ŠIPK, bo treba skupaj s končnim poročilom, ki ga moramo oddati do 3. oktobra, pripraviti tudi javno delujočo različico portala. To pomeni:
* kolikor toliko dodelana grafična podoba (vključno z vsemi aplikacijami, ki bodo vključene)
* vključitev vseh novih oziroma prenovljenih aplikacij v tolikšni meri, da bo objavljeni del dokončan (tj., brez morebitnih nedokončanih funkcionalnosti)
* povezave do delujočih zunanjih aplikacij (@db1456, @zanvd)

Kar še ne bo dokončano do takrat, se lahko vključi naknadno.

Vse torej prosim, da poveste, v kolikšni meri bodo do konca meseca pripravljene vaše aplikacije, da vemo, kaj bomo sedaj vključili.

/CC @AnzeVersnik @Krucifiks @mcafuta

**Comment by mcafuta** [comment]
Zivjo,

Moj del (vegenere) trenutno lokalno deluje brez povezave na bazo (torej hardcodan text in nekaj gesel). Lahko posljem projekt/ga dam na svoj github, na masterja raje ne bi, ker ne vem kaj narediti ce bodo kaki konflikti.. Plan je bil do konca meseca implementirati se preverjanje resitve in ce bo uspelo tudi pomoc uporabniku (drugace bi to dodala kasneje..).

Lp Manja

**Comment by zanvd** [comment]
Živjo,

portal za evolitve bo do konca meseca narejen do te mere, da bo mogoča administracija vprašalnikov in tudi njihovo izpolnjevanje (torej admin in user del). Tako da ostane še anonimnost, za katero pa bi rajši dal realno oceno, da bo vključena naknadno.

Za cilj pri izdelavi sem si zadal tudi to, da se ga bo dalo zapakirati kot paket in nato prenesti na drug strežnik brez večjega napora.

Lp,
Žan

**Comment by db1456** [comment]
Zdravo!

Jaz moram za aplikacijo za časovni žig dokončati še podpisovanje s certifikatom ter posodobiti grafično podobo stran na nov izgled. Upam, da mi bo do konca meseca uspelo, če ne pa se lahko izda verzija, kjer so podatki zapisani v navadno tekstovno datoteko, dokler ne bo dokončano ostalo.

Lep pozdrav,
Damir

**Comment by jaanos** [comment]
@mcafuta: kar naredi novo vejo iz veje `work` (lahko na svojem forku), pa daj tja svojo aplikacijo. Na `master` tako ali tako ni mogoče direktno pushati.

@zanvd, @db1456: V redu, vidva kar dokončajta svoje. Je pa seveda edino smiselno, da se dodajo povezave, če bosta aplikaciji dosegli svoj prvotni namen (torej anonimnost oziroma podpisovanje z ustreznim certifikatom).

**Comment by blazkablatnik** [comment]
Živjo,

aplikacija "alphabet" bo delovala po zadanih ciljih. Prilagojeno je delovanje za mobilne naprave (vsaj novejše), dodani sta dve novi generični stopnji, popravljen izgled... Ostaja samo še dokončna prilagoditev za grško abecedo (problem: velike in male črke, več črk za en znak).

Lp,
Blažka

**Comment by nani-dev** [comment]
Živjo,

aplikacija kriptografija je vec ali manj narejena do konca( koda je bila popolnoma na novo napisana, da igra deluje na tablicah ter telefonih), dodani so bili grafi za lazje resevanje, ter timer, kateri te po koncani igri uvrsti na leaderboard. Je pa nekaj malenkosti iz strani design-a, ki bi se dale še popravit oz. izboljšat.

**Comment by mcafuta** [comment]
Zivjo,

Se opravicujem za pozen odgovor, ocitno sem spregledala odgovor. Na noben nacin mi ni uspelo narediti nove veje/uploadati svojega dela aplikacije na https://github.com/jaanos/crypto-portal/, moja zadnja verzija tako ostaja na https://github.com/mcafuta/CP/tree/master. Dodane so datoteke: vigenere.py, vigenere.js, vigenere.css, vigenere.play.html in
vigenere.ready.html, spremenjeni pa se header.html in crypto.js

Lp Manja
